apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-repo
spec:
  hosts:
  - todo-repo
  http:
  - match:
    - headers:
        end-user:
          exact: batman
    fault:
      delay:
        percent: 100
        fixedDelay: 7s
    route:
    - destination:
        host: todo-repo
        subset: v1
  - route:
    - destination:
        host: todo-repo
        subset: v1
