apiVersion: v1
kind: Service
metadata:
  name: todo-repo
  labels:
    app: todo-repo
spec:
  ports:
  - name: http
    port: 8081
  selector:
    app: todo-repo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-repo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-repo
        version: v1
    spec:
      containers:
      - image: atsistemas/todo-repo:latest
        imagePullPolicy: IfNotPresent
        name: todo-repo
        ports:
        - containerPort: 8081
