apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-repo
  labels:
    app: todo-repo
spec:
  hosts:
  - todo-repo
  http:
  - fault:
      delay:
        percent: 80
        fixedDelay: 7s
    route:
    - destination:
        host: todo-repo
        subset: delay
  - route:
    - destination:
        host: todo-repo
        subset: delay
