apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-client
spec:
  hosts:
  - "*"
  gateways:
  - todo-client-gateway
  http:
  - fault:
      abort:
        percent: 20
        httpStatus: 400
    route:
    - destination:
        host: todo-client
        port:
          number: 8082
