apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-repo
  labels:
    app: todo-repo
spec:
  hosts:
  - todo-repo
  http:
  - fault:
      abort:
        percent: 50
        httpStatus: 404
    route:
    - destination:
        host: todo-repo
        subset: http-errors
  - route:
    - destination:
        host: todo-repo
        subset: http-errors