#!/usr/bin/env bash
set -e
set -x

# oc login
oc login -u admin -p password https://console.192.168.77.21.nip.io:8443/ --insecure-skip-tls-verify

# enable containers running with UID 0 for Istio’s service accounts:
oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z default -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-egressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-citadel-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-ingressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-cleanup-old-ca-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-post-install-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-pilot-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-sidecar-injector-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-galley-service-account -n istio-system
oc adm policy add-scc-to-user privileged -z default -n istio-system
oc adm policy add-scc-to-user privileged -z default -n default

# install istio
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.0.5 sh -

oc apply -f istio-1.0.5/install/kubernetes/helm/helm-service-account.yaml

#install helm
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | sh -
helm init --service-account tiller

sleep 30

helm install istio-1.0.5/install/kubernetes/helm/istio \
                                                    --name istio \
                                                    --namespace istio-system \
                                                    --set kiali.enabled=true \
                                                    --set mixer.telemetry.enabled=false

oc expose svc/kiali -n istio-system

oc policy add-role-to-user view system:serviceaccount:istio-system:kiali-service-account -n default
oc policy add-role-to-user view system:serviceaccount:istio-system:kiali-service-account -n istio-system
oc policy add-role-to-user view system:serviceaccount:istio-system:kiali-service-account -n management-infra

oc expose svc/istio-ingressgateway  -n istio-system

export GATEWAY_URL=$(oc get route -n istio-system istio-ingressgateway -o jsonpath='{.spec.host}')

echo $GATEWAY_URL